# Generated by Django 5.0.3 on 2024-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ans1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ans2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ans3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ans4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=100)),
            ],
        ),
    ]
