# Generated by Django 5.0.3 on 2024-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCapp', '0002_ans1_ans2_ans3_ans4_section1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ans1',
        ),
        migrations.DeleteModel(
            name='ans2',
        ),
        migrations.DeleteModel(
            name='ans3',
        ),
        migrations.DeleteModel(
            name='ans4',
        ),
        migrations.AddField(
            model_name='section1',
            name='answer',
            field=models.CharField(default='answer', max_length=2000),
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='section1',
            name='quest',
            field=models.CharField(default='Question', max_length=2000),
        ),
    ]
