# Generated by Django 5.0.3 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCapp', '0006_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(default='Question', max_length=2000)),
                ('answer', models.CharField(default='answer', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(default='Question', max_length=2000)),
                ('answer', models.CharField(default='answer', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Section4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(default='Question', max_length=2000)),
                ('answer', models.CharField(default='answer', max_length=2000)),
            ],
        ),
    ]
