# Generated by Django 5.0.3 on 2024-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCapp', '0008_results_best_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('Option1C', models.CharField(max_length=1000)),
                ('Option1D', models.CharField(max_length=1000)),
                ('Option1B', models.CharField(max_length=1000)),
                ('Option1P', models.CharField(max_length=1000)),
                ('Option2C', models.CharField(max_length=1000)),
                ('Option2D', models.CharField(max_length=1000)),
                ('Option2B', models.CharField(max_length=1000)),
                ('Option2P', models.CharField(max_length=1000)),
                ('Option3C', models.CharField(max_length=1000)),
                ('Option3D', models.CharField(max_length=1000)),
                ('Option3B', models.CharField(max_length=1000)),
                ('Option3P', models.CharField(max_length=1000)),
            ],
        ),
    ]
